"use client";

import React, { useState } from "react";
import { Code2, Terminal, Copy, CheckCircle2, Shield, FileCode, Check } from "lucide-react";

export const CompactCircuitViewer: React.FC = () => {
  const [activeTab, setActiveTab] = useState<"compact" | "witness" | "nullifier">("compact");
  const [copied, setCopied] = useState(false);

  const compactCode = `// Midnight Compact Smart Contract: vox_midnight.compact
export ledger proposalId: Uint<32>;
export ledger yesCount: Counter;
export ledger noCount: Counter;
export ledger totalVotes: Counter;
export ledger votingActive: Boolean;
export ledger admin: Bytes<32>;
export ledger nullifiers: Map<Bytes<32>, Boolean>;

// Private Witnesses (Client-Side Prover Sandbox)
witness voterChoiceWitness(): Boolean;
witness voterSecretWitness(): Bytes<32>;
witness voterEligibilityWitness(): Uint<16>;

export circuit castBallot(nullifierHash: Bytes<32>): Boolean {
    assert votingActive "Governance voting is currently closed or resolved";
    assert !nullifiers.member(nullifierHash) "Nullifier already spent: Double-voting forbidden";

    const choice = voterChoiceWitness();
    const secret = voterSecretWitness();
    const eligibilityScore = voterEligibilityWitness();

    assert eligibilityScore > 0 "Voter has insufficient governance weight";

    // Disclose ONLY tally counters & nullifier to public ledger
    const isYes: Boolean = disclose(choice);
    const disclosedNullifier: Bytes<32> = disclose(nullifierHash);

    if (isYes) {
        yesCount.increment(1);
    } else {
        noCount.increment(1);
    }
    totalVotes.increment(1);
    nullifiers.insert(disclosedNullifier, true);

    return true;
}`;

  const witnessExplanation = `// Local Client-Side Witness Ingestion Pipeline:
// 1. voterChoiceWitness() -> Raw boolean selection (True for Approve, False for Reject)
// 2. voterSecretWitness() -> 256-bit cryptographic entropy salt generated by Lace Wallet
// 3. voterEligibilityWitness() -> Verified DAO token balance proof from local state
//
// These 3 witnesses NEVER exit the user's browser runtime. They are digested
// exclusively through the Halo2 proving circuit to generate an anonymous proof.`;

  const nullifierExplanation = `// Double-Voting Prevention Mechanism (Cryptographic Nullifier):
//
// Nullifier = SHA-256( voterSecret || proposalId )
//
// 1. Unlinkable: You cannot determine the voter's public address or secret from the nullifier.
// 2. Deterministic: Attempting to vote again on the same proposal with the same secret
//    yields the EXACT same nullifier.
// 3. Collision-Resistant: The Compact ledger asserts !nullifiers.member(nullifierHash).`;

  const getActiveCode = () => {
    switch (activeTab) {
      case "witness":
        return witnessExplanation;
      case "nullifier":
        return nullifierExplanation;
      default:
        return compactCode;
    }
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(getActiveCode());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="glass-panel rounded-3xl p-6 sm:p-8 border border-white/10 shadow-2xl">
      {/* Header */}
      <div className="flex flex-wrap items-center justify-between gap-3 mb-6 pb-4 border-b border-white/10">
        <div className="flex items-center space-x-3">
          <div className="w-10 h-10 rounded-2xl bg-cyan-500/15 border border-cyan-500/30 flex items-center justify-center">
            <FileCode className="w-5 h-5 text-cyan-400" />
          </div>
          <div>
            <h3 className="text-lg font-bold text-white tracking-tight flex items-center space-x-2">
              <span>Compact Smart Contract Architecture</span>
              <span className="px-2 py-0.5 text-[9px] uppercase tracking-wider font-mono rounded bg-cyan-500/20 text-cyan-300 border border-cyan-500/30">
                Compact DSL
              </span>
            </h3>
            <p className="text-xs text-slate-400">Formal Zero-Knowledge Specification for VoxMidnight</p>
          </div>
        </div>

        {/* Copy Button */}
        <button
          onClick={handleCopy}
          className="flex items-center space-x-1.5 px-3 py-1.5 rounded-xl bg-obsidian-800 hover:bg-obsidian-700 text-xs text-slate-300 border border-white/10 transition"
        >
          {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
          <span>{copied ? "Copied" : "Copy Code"}</span>
        </button>
      </div>

      {/* Tabs */}
      <div className="flex space-x-2 mb-4">
        <button
          onClick={() => setActiveTab("compact")}
          className={`px-4 py-2 rounded-xl text-xs font-semibold font-mono transition ${
            activeTab === "compact"
              ? "bg-cyan-500/20 text-cyan-300 border border-cyan-500/40"
              : "bg-obsidian-800 text-slate-400 hover:text-slate-200 border border-white/5"
          }`}
        >
          vox_midnight.compact
        </button>
        <button
          onClick={() => setActiveTab("witness")}
          className={`px-4 py-2 rounded-xl text-xs font-semibold font-mono transition ${
            activeTab === "witness"
              ? "bg-lunar-teal/20 text-lunar-teal border border-lunar-teal/40"
              : "bg-obsidian-800 text-slate-400 hover:text-slate-200 border border-white/5"
          }`}
        >
          Private Witnesses
        </button>
        <button
          onClick={() => setActiveTab("nullifier")}
          className={`px-4 py-2 rounded-xl text-xs font-semibold font-mono transition ${
            activeTab === "nullifier"
              ? "bg-purple-500/20 text-purple-300 border border-purple-500/40"
              : "bg-obsidian-800 text-slate-400 hover:text-slate-200 border border-white/5"
          }`}
        >
          Nullifier Math
        </button>
      </div>

      {/* Code Display */}
      <div className="p-4 rounded-2xl bg-obsidian-950 border border-white/5 overflow-x-auto">
        <pre className="text-xs font-mono text-slate-300 leading-relaxed">
          <code>{getActiveCode()}</code>
        </pre>
      </div>
    </div>
  );
};
